ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"
ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = ""
default_platform(:ios)
platform :ios do
  lane :build do
    #scan
    cert
    sigh
    gym(
      export_options: {
        provisioningProfiles: {
            "gosu1902.AppCommonServices": "AppCommonServices Provisioning Profile",
            "gosu1902.AppCommonServices.CustomNotificationUI": "AppCommonServices CustomNotificationUI Provisionin",
            "gosu1902.AppCommonServices.PayloadModification": "AppCommonServices Payload Provisioning Profile"
        }
    }
    )
  end
  lane :alpha do
    build
    pilot
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })
  end
  lane :release do
    build
    deliver
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })
  end
end