name: Run tests
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install fastlane
        run: |
          bundle install
      - name: Execute fastlane
        run: |
          bundle exec fastlane testCI
